name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pylint structlog
      - name: Run Code Analysis Tests
        run: pytest tests/integration/test_code_analysis.py -v
      - name: Validate Metrics Post-Test
        run: |
          # Verifica se métricas OpenTelemetry estão registradas
          METRICS_OUTPUT=$(curl -s http://localhost:8000/metrics)
          echo "$METRICS_OUTPUT" | grep "celery_task_duration_seconds"
      - name: Store Test Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports
          path: test-reports/
      - name: Run Security Scan
        run: |
          pip install bandit
          bandit -r src/ -f json -o bandit.json
      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit.json

  stress_tests:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pylint structlog
      - name: Stress Tests
        run: pytest tests/integration/test_code_analysis.py -m stress

  log_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Structured Logs
        run: cat src/logs/app.log | jq empty
        env:
          LOG_LEVEL: DEBUG 