name: CI

on:
  push:
    branches: [ main, develop ]
    tags: ['v*']
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.8'
  REDIS_MAXMEMORY: 256mb
  REDIS_MAXMEMORY_POLICY: allkeys-lru
  DOCKER_IMAGE: refactool
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
        
    - name: Format with black
      run: black .
      
    - name: Check formatting
      run: black . --check --diff
      
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics --max-complexity=10
        
    - name: Commit formatting changes
      if: github.event_name == 'pull_request'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "style: format code with black"
        git push

  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        
    - name: Type check
      run: |
        mypy api tests --ignore-missing-imports

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_MAXMEMORY: ${{ env.REDIS_MAXMEMORY }}
          REDIS_MAXMEMORY_POLICY: ${{ env.REDIS_MAXMEMORY_POLICY }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        
    - name: Run unit tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v tests/ -m "unit" --cov=api --cov-report=xml --cov-report=html --junitxml=unit-test-results.xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: |
          coverage.xml
          htmlcov
          unit-test-results.xml
        retention-days: 7

  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_MAXMEMORY: ${{ env.REDIS_MAXMEMORY }}
          REDIS_MAXMEMORY_POLICY: ${{ env.REDIS_MAXMEMORY_POLICY }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        
    - name: Start Celery worker
      run: |
        celery -A api.src.tasks worker --loglevel=info --pool=solo &
        sleep 5
        
    - name: Run integration tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v tests/ -m "integration" --cov=api --cov-report=xml --cov-report=html --junitxml=integration-test-results.xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: |
          coverage.xml
          htmlcov
          integration-test-results.xml
        retention-days: 7

  system-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_MAXMEMORY: ${{ env.REDIS_MAXMEMORY }}
          REDIS_MAXMEMORY_POLICY: ${{ env.REDIS_MAXMEMORY_POLICY }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        
    - name: Start Celery worker
      run: |
        celery -A api.src.tasks worker --loglevel=info --pool=solo &
        sleep 5
        
    - name: Run system tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v tests/ -m "system" --cov=api --cov-report=xml --cov-report=html --junitxml=system-test-results.xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: system-test-results
        path: |
          coverage.xml
          htmlcov
          system-test-results.xml
        retention-days: 7

  stress-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          REDIS_MAXMEMORY: ${{ env.REDIS_MAXMEMORY }}
          REDIS_MAXMEMORY_POLICY: ${{ env.REDIS_MAXMEMORY_POLICY }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        
    - name: Start Celery worker
      run: |
        celery -A api.src.tasks worker --loglevel=info --pool=solo &
        sleep 5
        
    - name: Run stress tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest -v tests/ -m "stress" --cov=api --cov-report=xml --cov-report=html --junitxml=stress-test-results.xml
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: stress-test-results
        path: |
          coverage.xml
          htmlcov
          stress-test-results.xml
        retention-days: 7

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety pip-audit
        
    - name: Run security scans
      run: |
        bandit -r . -f json -o security-report.json -ll --exclude tests/,docs/ || true
        safety check -r requirements.txt --json > dependencies-report.json || true
        pip-audit --requirement requirements.txt --format json > audit-report.json || true
        
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          security-report.json
          dependencies-report.json
          audit-report.json
        retention-days: 7
        
    - name: Check for critical vulnerabilities
      run: |
        if grep -q '"level": "HIGH"' security-report.json; then
          echo "Critical security issues found!"
          exit 1
        fi
        if grep -q '"severity": "critical"' dependencies-report.json; then
          echo "Critical dependencies vulnerabilities found!"
          exit 1
        fi
        if grep -q '"severity": "Critical"' audit-report.json; then
          echo "Critical audit issues found!"
          exit 1
        fi

  publish:
    needs: [lint, type-check, unit-tests, integration-tests, system-tests, stress-tests, security]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        
    - name: Build package
      run: python -m build
      
    - name: Publish to TestPyPI
      if: github.ref == 'refs/heads/main'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        verbose: true
        print-hash: true
        
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        verbose: true
        print-hash: true

  docker:
    needs: [lint, type-check, unit-tests, integration-tests, system-tests, stress-tests, security]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:buildcache,mode=max
        
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}
        short-description: Analisador de código com cache distribuído e alta performance
        readme-filepath: ./README.md