name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pylint

      - name: Run Linter (Pylint)
        run: |
          find . -type f -name '*.py' | xargs pylint --exit-zero

      - name: Run Unit & Integration Tests (Pytest)
        run: |
          pytest tests/ --cov=src --cov-report=term-missing --cov-report=xml

      - name: Security Audit (Bandit)
        run: |
          pip install bandit
          bandit -r src -ll

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml 