name: Publicar no PyPI

on:
  push:
    tags:
      - 'v*'  # Aciona o workflow quando uma tag começando com 'v' é criada

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Construir pacote
      run: python -m build
    
    - name: Publicar no TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      run: |
        twine upload --skip-existing dist/*
    
    - name: Publicar no PyPI
      if: success()  # Só executa se o TestPyPI foi bem sucedido
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/* 