name: Publicar no PyPI

on:
  push:
    tags:
      - 'v*'  # Aciona o workflow quando uma tag começando com 'v' é criada

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Construir e verificar pacote
      run: |
        python -m build
        twine check dist/*
    
    - name: Publicar no TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
    
    - name: Publicar no PyPI
      if: startsWith(github.ref, 'refs/tags/')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }} 