name: Publicar no PyPI

on:
  push:
    tags:
      - 'v*'  # Aciona o workflow quando uma tag começando com 'v' é criada

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Construir pacote
      run: python -m build
    
    - name: Verificar estrutura do pacote
      run: |
        ls -la dist/
        twine check dist/*
    
    - name: Verificar token do TestPyPI
      run: |
        if [ -z "$PYPI_TEST_TOKEN" ]; then
          echo "::error::PYPI_TEST_TOKEN não está definido"
          exit 1
        else
          echo "PYPI_TEST_TOKEN está definido"
        fi
      env:
        PYPI_TEST_TOKEN: ${{ secrets.PYPI_TEST_TOKEN }}
    
    - name: Publicar no TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      run: |
        echo "Tentando fazer upload para TestPyPI..."
        echo "Token length: ${#TWINE_PASSWORD}"
        python -m twine upload --verbose --skip-existing dist/*
    
    - name: Publicar no PyPI
      if: success()  # Só executa se o TestPyPI foi bem sucedido
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        echo "Tentando fazer upload para PyPI..."
        python -m twine upload --verbose dist/* 